# lmao
# initially needed an LLM to write 75% of this for me though, shame.
name: build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # who the hell is casting hexes on a mac?
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v6

      - name: get rust
        uses: dtolnay/rust-toolchain@stable

      - name: build everythin
        run: cargo build --release

      - name: move executable (linux/mac)
        if: matrix.os != 'windows-latest'
        run: mv target/release/encoder ./encoder

      # bein fr i never use powershell like ever
      # i only use command prompt
      - name: move executable (windows)
        if: matrix.os == 'windows-latest'
        run: move target/release/encoder.exe encoder.exe

      - name: upload (linux/mac)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v6
        with:
          name: encoder-${{ matrix.os }}
          path: |
            encoder
            needs/
            examples/
            README.md
      
      - name: upload (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v6
        with:
          name: encoder-${{ matrix.os }}
          path: |
            encoder.exe
            needs/
            examples/
            README.md